# Generated by Django 3.1.3 on 2021-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='blog_image'),
            preserve_default=False,
        ),
    ]
